name 'surfspots'
maintainer 'Patrick B'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures surfspots'
long_description 'Installs/Configures surfspots'
version '0.9.0'

depends 'httpd', '~> 0.3.0'
depends 'selinux', '~> 0.9.0'
depends 'iptables', '~> 1.0.0'
depends 'mysql2_chef_gem', '~> 1.0.1'
depends 'mysql', '~> 6.0.17'
depends 'database', '~> 4.0.3'